### ISSUE TITLE
help with install

### ISSUE THREAD

**Issue by a1nb0** [itemsapi/itemsjs#11]
Hi @cigolpl,

great job  with this one.

I am trying to replicate a search app like http://devteams.co/ on localhost but i have trouble making it work.
I have looked at the documentation but it seems i am doing something  wrong.

Could you provide a step by step clear instruction on how to make it run localhost?

Thank you so much

**Comment by cigolpl** [comment]
Hello @a1nb0,

Thank you! Sorry if the documentation is not helpful. I am doing lot of experiments to find a best solutions so many things might become outdated after some time.

If you'd like to replicate devteams.co there are three solutions:

- you can use this example https://jsfiddle.net/cigol/0ef9qeos/5/ and just customize for your need. It's using Vue.js and ItemsJS (search engine in javascript). It's good but only for a small dataset (up to a few thousands items I guess)

- you can use https://github.com/itemsapi/curlist which is more sophisticated because it's using Elasticsearch and PostgreSQL and it's more powerful because it has more features for processing and searching data. It's still new and I'd say it's alpha. I'll create a new version of http://devteams.co/ with this software soon. I could let you know if I make next progress (i.e. writing some tutorials step by step instruction)

- you can also use https://github.com/itemsapi/starter which will generate for you an app like devteams on heroku but it's outdated for me and I am not gonna support it in the future

**Comment by a1nb0** [comment]
Hi @cigolpl,
thank you for a fast and helpful answer.
I am looking for something that can handle more than few thousands items so i decided to try the curlist.
And here is what i get  `git clone git@github.com:itemsapi/curlist.git
Cloning into 'curlist'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`
